title: Robin H. van der Weide
url: "https://robinweide.github.io"
baseurl: "/robinweide.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/robinweide"
#footer_text: "Page design based on  Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/robinweide.github.io/"
 - name: "Contact"
   link: "contact"
